### ISSUE TITLE
You are using my code and are not allowed to re-licence it as CC-BY

### ISSUE THREAD

**Issue by gavinsimpson** [aimundo/GAMs-biomedical-research#1]
The code of mine that you are using in your `difference_smooths` is taken directly from either my blog posts on comparing factor smooth interactions and on simultaneous intervals, or my package gratia.

Code on my blog is licensed for redistribution under the GPL version 2 license.

Code in gratia is licensed for redistribution under the MIT license.

Re-licencing this code under CC BY is not allowed under either license.

If you used code from my blog posts then I agree to your using this code under the MIT licence (assuming you follow the terms of that license) as that license is compatible with CC BY.

You need to remove and clean-room reimplement my code if you continue to want to licence your modifications to my code under CC BY. 

Alternatively, you can release the relevant script file under MIT (and follow the requirements of the that licence by including the LICENCE file in your distribution and noting my copyright over the code (and your copyright over the modifications)) while continuing to release the remainder of your code under CC BY.

**Comment by aimundo** [comment]
Hi Dr. Simpson, 

Thank you for reaching out, I appreciate your willingness to let me use the code you wrote for _gratia_ and in your blog, both have been tremendously helpful! Based on what you say, I think the best thing to do is to follow your suggestion of modifying the license for the script where `difference_smooths` is used, and add your copyright over the code. 
However, I would like to request that you are a little patient with me to implement the change, I just moved to a different country and in the next week or two I have a lot of paperwork and things to take care of, so my time in front of a computer is going to be somewhat limited, but I will try my best to work on this.
I'll keep this open and once I make the change I can notify you here to see if you agree, and if you do, I will close the issue.

Thank you for reaching out, and helping to make this work come to fruition. If you have any comments please let me know.

**Comment by aimundo** [comment]
I forgot to add that yes, we based the code on that script on your function from from _gratia_ (which we acknowledged on the README file).

**Comment by aimundo** [comment]
@gavinsimpson Please check the README and license files to see if you approve, they've been updated to include the requested changes.

**Comment by aimundo** [comment]
It's been a while since this issue was opened, since the license is now in place I will close the issue.
